### ISSUE TITLE
MCMC deconv broken

### ISSUE THREAD

**Issue by Samuel8789** [shymkivy/caiman_sorter#1]
When running MCMC:

Unrecognized function or variable 'sig_start'.

Error in f_cs_compute_MCMC (line 35)
    app.proc.deconv.MCMC.C{n_cell} = [zeros(1,sig_start-1), mean(SAMP.C_rec,1)];

Error in f_cs_deconvolution (line 26)
            f_cs_compute_MCMC(app, n_cell);

Error in caiman_sorter/RunallcellsButtonPushed (line 497)
            f_cs_deconvolution(app, app.idx_components_all);
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback (line 410)
Error while evaluating Button PrivateButtonPushedFcn.

**Comment by shymkivy** [comment]
ok, fixed code... dl new version or replace "sig_start" with "SAMP.sig_start" on that line
